### ISSUE TITLE
How it has to be the File configuration.xml

### ISSUE THREAD

**Issue by ascariz** [Riuujin/charpcomicviewer-sf#2]
I'm looking at the project and I would like to know how the mlx configuration file should be. Thank you

**Comment by Riuujin** [comment]
What "configuration.xml" do you mean?

**Comment by ascariz** [comment]
I'm trying to start the application and I get the blank screen, no menus appear or any other type of button. What is there to do?

**Comment by Riuujin** [comment]
You should always have a context menu (right click)

**Comment by ascariz** [comment]
I get the following error when I try to open a CBR.
Can not load 7-zip libray on internal COM error! Message: failed to load library

**Comment by Riuujin** [comment]
I am assuming you are building the project yourself and didn't use the installer.
If so you will have to manually add the correct "7z.dll" to the "CSharpComicViewer\bin\Debug". These can be found in the "Resources" folder.
